CREATE TABLE [ACAOUSUARIO] (
    [CODIGO]        INT           NOT NULL,
    [CODIGOUSUARIO] INT           DEFAULT ((0)) NOT NULL,
    [ACAO]          VARCHAR (200) DEFAULT ('') NOT NULL,
    [DATAREGISTRO]  DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

