CREATE TABLE [BIOMAS] (
    [ID]              INT            NOT NULL,
    [NOME]            VARCHAR (200)  NULL,
    [DISTRIBUICAO]    VARCHAR (200)  NULL,
    [CARACTERISTICAS] VARCHAR (8000) NULL,
    [FITOFISIONOMIA]  VARCHAR (8000) NULL,
    [OBSERVACAO]      VARCHAR (8000) NULL,
    [IDUSUARIO]       INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IDUSUARIO]) REFERENCES [USUARIOS] ([ID])
);

