CREATE TABLE [CAMPOS] (
    [CODIGO]       INT             DEFAULT ((0)) NOT NULL,
    [CODIGOTABELA] INT             DEFAULT ((0)) NOT NULL,
    [NOME]         VARCHAR (50)    DEFAULT ('') NOT NULL,
    [CHAVE]        CHAR (1)        DEFAULT ('0') NOT NULL,
    [DOMINIO]      VARCHAR (100)   DEFAULT ('') NOT NULL,
    [CODIGOTIPO]   INT             DEFAULT ((0)) NOT NULL,
    [NAONULO]      CHAR (1)        DEFAULT ('0') NOT NULL,
    [UNICO]        CHAR (1)        DEFAULT ('0') NOT NULL,
    [CHECAR]       VARCHAR (300)   DEFAULT ('') NOT NULL,
    [PADRAO]       VARCHAR (300)   DEFAULT ('') NOT NULL,
    [COMENTARIO]   VARCHAR (900)   DEFAULT ('') NOT NULL,
    [TAMANHO]      INT             DEFAULT ((0)) NOT NULL,
    [PRECISAO]     DECIMAL (15, 4) DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC, [CODIGOTABELA] ASC, [NOME] ASC, [CHAVE] ASC, [DOMINIO] ASC, [CODIGOTIPO] ASC, [NAONULO] ASC, [UNICO] ASC, [CHECAR] ASC, [PADRAO] ASC, [COMENTARIO] ASC, [TAMANHO] ASC, [PRECISAO] ASC)
);

