CREATE TABLE [CARTAOCREDITODEVTOOLS] (
    [NUMEROCARTAO]    VARCHAR (100) DEFAULT ('') NOT NULL,
    [DATAVALIDADE]    VARCHAR (50)  DEFAULT ('') NOT NULL,
    [CODIGOSEGURANCA] CHAR (3)      DEFAULT ('') NOT NULL,
    [CREATED]         VARCHAR (50)  DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMEROCARTAO] ASC)
);

