CREATE TABLE [CLIENTES] (
    [CODIGO]       INT            DEFAULT ((0)) NOT NULL,
    [RAZAOSOCIAL]  VARCHAR (1000) DEFAULT ('') NOT NULL,
    [NOMEFANTASIA] VARCHAR (1000) DEFAULT ('') NOT NULL,
    [CNPJ]         CHAR (18)      DEFAULT ('') NOT NULL,
    [CIDADE]       VARCHAR (500)  DEFAULT ('') NOT NULL,
    [ESTADO]       CHAR (2)       DEFAULT ('') NOT NULL,
    [ENDERECO]     VARCHAR (1000) DEFAULT ('') NOT NULL,
    [CEP]          VARCHAR (8)    DEFAULT ('') NOT NULL,
    [EMAIL]        CHAR (500)     DEFAULT ('') NOT NULL,
    [TELEFONE]     VARCHAR (30)   NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

