CREATE TABLE [CONFIGURACAOEMAIL] (
    [CODIGO]          INT           NOT NULL,
    [EMAILREMETENTE]  VARCHAR (300) DEFAULT ('') NOT NULL,
    [SMTPCLIENT]      VARCHAR (100) NULL,
    [PORTA]           INT           DEFAULT ((587)) NOT NULL,
    [EMAILCREDENCIAL] VARCHAR (300) DEFAULT ('') NOT NULL,
    [SENHACREDENCIAL] VARCHAR (200) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

