CREATE TABLE [CONTABANCOFORDEV] (
    [CREATED]       VARCHAR (50)  DEFAULT ('') NOT NULL,
    [CONTACORRENTE] VARCHAR (100) DEFAULT ('') NOT NULL,
    [AGENCIA]       VARCHAR (50)  DEFAULT ('') NOT NULL,
    [BANCO]         VARCHAR (50)  DEFAULT ('') NOT NULL,
    [CIDADE]        VARCHAR (150) DEFAULT ('') NOT NULL,
    [ESTADO]        CHAR (2)      DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([CONTACORRENTE] ASC)
);

