CREATE TABLE [DESPESAS] (
    [CODIGO]       INT           NOT NULL,
    [DATAINSERCAO] DATETIME      NOT NULL,
    [DATADESPESA]  VARCHAR (30)  DEFAULT ('') NOT NULL,
    [DESCRICAO]    VARCHAR (300) DEFAULT ('') NOT NULL,
    [CATEGORIA]    VARCHAR (30)  DEFAULT ('') NOT NULL,
    [VALOR]        VARCHAR (30)  DEFAULT ('') NOT NULL,
    [CONTA]        VARCHAR (300) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

