CREATE TABLE [EMAILANEXOS] (
    [CODIGO]      INT           NOT NULL,
    [CODIGOEMAIL] INT           DEFAULT ((0)) NOT NULL,
    [ARQUIVO]     VARBINARY (1) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

