CREATE TABLE [IMAGENSBIOMA] (
    [ID]        INT           NOT NULL,
    [IDBIOMA]   INT           NOT NULL,
    [CAMINHO]   VARCHAR (300) NULL,
    [IDUSUARIO] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IDBIOMA]) REFERENCES [BIOMAS] ([ID]),
    FOREIGN KEY ([IDUSUARIO]) REFERENCES [USUARIOS] ([ID])
);

