CREATE TABLE [IMAGENSPLANTA] (
    [ID]        INT           NOT NULL,
    [IDPLANTA]  INT           NOT NULL,
    [CAMINHO]   VARCHAR (300) NULL,
    [IDUSUARIO] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([IDPLANTA]) REFERENCES [PLANTAS] ([ID]),
    FOREIGN KEY ([IDUSUARIO]) REFERENCES [USUARIOS] ([ID])
);

