CREATE TABLE [MODULOS] (
    [CODIGO]            INT            DEFAULT ((0)) NOT NULL,
    [NOMEMODULO]        VARCHAR (100)  DEFAULT ('') NOT NULL,
    [DESCRICAO]         VARCHAR (1000) NULL,
    [SEQUENCIAABERTURA] VARCHAR (1000) NULL,
    [CODIGOPROJETO]     INT            DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC, [CODIGOPROJETO] ASC)
);

