CREATE TABLE [PALAVRAS] (
    [ID]      INT           NOT NULL,
    [NIVEL]   INT           NOT NULL,
    [PALAVRA] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([PALAVRA] ASC)
);

