CREATE TABLE [PROJETO] (
    [CODIGO]    INT           DEFAULT ((0)) NOT NULL,
    [NOME]      VARCHAR (50)  DEFAULT ('') NOT NULL,
    [DESCRICAO] VARCHAR (400) NULL,
    [STATUS]    CHAR (1)      NULL,
    [GIT]       VARCHAR (200) DEFAULT ('-') NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

