CREATE TABLE [RECUPERASENHACONCURSANDO] (
    [CODIGO]       INT           NOT NULL,
    [DATAREGISTRO] DATETIME      NOT NULL,
    [GUID]         VARCHAR (64)  DEFAULT ('') NOT NULL,
    [EMAIL]        VARCHAR (300) DEFAULT ('') NOT NULL,
    [RECUPERADO]   CHAR (1)      DEFAULT ('0') NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

