CREATE TABLE [TABELA] (
    [CODIGO]    INT           DEFAULT ((0)) NOT NULL,
    [PROJETO]   INT           DEFAULT ((0)) NOT NULL,
    [NOME]      VARCHAR (50)  DEFAULT ('') NOT NULL,
    [DESCRICAO] VARCHAR (400) NULL,
    [NOTAS]     VARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC, [PROJETO] ASC)
);

