CREATE TABLE [TABELASMODULOS] (
    [CODIGOTABELA] INT DEFAULT ((0)) NOT NULL,
    [CODIGOCAMPO]  INT DEFAULT ((0)) NOT NULL,
    [CODIGOMODULO] INT DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGOTABELA] ASC, [CODIGOCAMPO] ASC, [CODIGOMODULO] ASC)
);

