CREATE TABLE [TABELAS] (
    [TAB]   VARCHAR (40) DEFAULT ('') NOT NULL,
    [FIELD] VARCHAR (25) DEFAULT ('') NOT NULL,
    [TYPE]  CHAR (1)     DEFAULT ('') NOT NULL,
    [SIZE]  INT          DEFAULT ((0)) NOT NULL,
    [PREC]  INT          DEFAULT ((0)) NOT NULL,
    [FLAG]  INT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([TAB] ASC, [FIELD] ASC, [TYPE] ASC, [SIZE] ASC, [PREC] ASC, [FLAG] ASC)
);

