CREATE TABLE [TRADUCOES] (
    [CODIGO]           INT           NOT NULL,
    [DATAREGISTRO]     DATETIME      NOT NULL,
    [PALAVRAPORTUGUES] VARCHAR (300) DEFAULT ('') NOT NULL,
    [PALAVRAINGLES]    VARCHAR (300) DEFAULT ('') NOT NULL,
    [CLASSEGRAMATICAL] VARCHAR (100) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

