CREATE TABLE [dbo].[USUARIOS](
	[ID] [int] NOT NULL,
	[LOGIN] [varchar](50) NOT NULL,
	[PASS] [varchar](12) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[Email] [varchar](300) NULL,
	[DataNascimento] [date] NULL,
	[Admin] [char](1) NULL,
	[Created] [datetime] NULL,
	[Updated] [datetime] NULL,
	[INSTITUICAO] [nvarchar](255),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[LOGIN] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USUARIOS] ADD  DEFAULT ('0') FOR [Admin]
GO

