CREATE TABLE [VEICULOSFORDEV] (
    [MARCA]        VARCHAR (300) DEFAULT ('') NOT NULL,
    [MODELO]       VARCHAR (300) DEFAULT ('') NOT NULL,
    [ANO]          VARCHAR (10)  DEFAULT ('') NOT NULL,
    [RENAVAM]      VARCHAR (30)  DEFAULT ('') NOT NULL,
    [PLACAVEICULO] VARCHAR (20)  DEFAULT ('') NOT NULL,
    [COR]          VARCHAR (50)  DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([RENAVAM] ASC)
);

