CREATE TABLE [VERBOS] (
    [CODIGO]       INT           NOT NULL,
    [PALAVRA]      VARCHAR (500) DEFAULT ('') NOT NULL,
    [DATAINSERCAO] DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

