CREATE TABLE [VERBOCONJUGADO] (
    [CODIGO]                   INT           NOT NULL,
    [DATACRIACAO]              DATETIME      NOT NULL,
    [VERBO]                    VARCHAR (500) DEFAULT ('') NOT NULL,
    [PRESENTE]                 VARCHAR (500) DEFAULT ('') NOT NULL,
    [PRETERITOIMPERFEITO]      VARCHAR (500) DEFAULT ('') NOT NULL,
    [PRETERITOPERFEITO]        VARCHAR (500) DEFAULT ('') NOT NULL,
    [PRETERITOMAISQUEPERFEITO] VARCHAR (500) DEFAULT ('') NOT NULL,
    [FUTURODOPRESENTE]         VARCHAR (500) DEFAULT ('') NOT NULL,
    [FUTURODOPRETERITO]        VARCHAR (500) DEFAULT ('') NOT NULL,
    [PRONOME]                  VARCHAR (30)  DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

