:r ../Tables/Usuarios.sql
:r ../Tables/Biomas.sql
:r ../Tables/Plantas.sql
:r ../Tables/Imagensbioma.sql
:r ../Tables/Imagensplanta.sql
:r ../Tables/Questoes.sql
:r ../Tables/Respostasquestoes.sql
:r ../Tables/AcaoUsuario.sql
:r ../Tables/Alimentos.sql
:r ../Tables/AnexoResposta.sql
:r ../Tables/AnexosQuestoes.sql
:r ../Tables/Apresentacao.sql
:r ../Tables/Automatico.sql
:r ../Tables/Avaliacao.sql
:r ../Tables/Campos.sql
:r ../Tables/Cartaocreditodevtools.sql
:r ../Tables/Categoriaalimentos.sql
:r ../Tables/Chavesjwt.sql
:r ../Tables/Clientes.sql
:r ../Tables/CodigosTable.sql
:r ../Tables/Comentariosquestoes.sql
:r ../Tables/Configuracaoemail.sql
:r ../Tables/Consultas.sql
:r ../Tables/Contabancofordev.sql
:r ../Tables/Crudformsinstalador.sql
:r ../Tables/Despesas.sql
:r ../Tables/Email.sql
:r ../Tables/Emailanexos.sql
:r ../Tables/Emailbackup.sql
:r ../Tables/Empresafordev.sql
:r ../Tables/Licencassunsalepro.sql
:r ../Tables/Logg.sql
:r ../Tables/Logger.sql
:r ../Tables/Metas.sql
:r ../Tables/Modulos.sql
:r ../Tables/Notascortesisu.sql
:r ../Tables/Oleosessenciais.sql
:r ../Tables/Palavras.sql
:r ../Tables/Parametros.sql
:r ../Tables/Pesos.sql
:r ../Tables/Pessoasfordev.sql
:r ../Tables/Postagem.sql
:r ../Tables/Projeto.sql
:r ../Tables/Prova.sql
:r ../Tables/Questoesavaliacao.sql
:r ../Tables/Receitas.sql
:r ../Tables/Recuperasenha.sql
:r ../Tables/Recuperasenhaconcursando.sql
:r ../Tables/Recuperasenhacrudforms.sql
:r ../Tables/Relacao.sql
:r ../Tables/Respostasavaliacoes.sql
:r ../Tables/Respostasusuarios.sql
:r ../Tables/Resultadossoletrando.sql
:r ../Tables/Resultadostabuadadivertida.sql
:r ../Tables/Savedresultswpp.sql
:r ../Tables/Simulados.sql
:r ../Tables/Tabela.sql
:r ../Tables/Tabelas.sql
:r ../Tables/Tabelasmodulos.sql
:r ../Tables/Temp1.sql
:r ../Tables/Teste.sql
:r ../Tables/Tipocampo.sql
:r ../Tables/Tipoperfil.sql
:r ../Tables/Tipopostagem.sql
:r ../Tables/Tipoprova.sql
:r ../Tables/Tipoprovaassociado.sql
:r ../Tables/Tiposuporte.sql
:r ../Tables/Traducoes.sql
:r ../Tables/Usuarioconcursando.sql
:r ../Tables/Usuarioscrudforms.sql
:r ../Tables/Veiculosfordev.sql
:r ../Tables/Verboconjugado.sql
:r ../Tables/Verbos.sql
:r ../Tables/Verificacaousuario.sql
:r ../Tables/Versao.sql
:r ../Tables/Whosthatpokemonresult.sql
