CREATE TABLE [dbo].[Alimentos]
(
	[Id] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Categoriacodigo] [bigint] NOT NULL,
    [Created] DATETIME NOT NULL DEFAULT GETDATE(),
    [Updated] DATETIME NOT NULL DEFAULT GETDATE(),
    [IsActive] [tinyint] NOT NULL DEFAULT 1,
	[IsDeleted] [tinyint] NOT NULL DEFAULT 0,
	[Numeroalimento] [bigint] NOT NULL,
	[Descricao] VARCHAR(255) NOT NULL,
	[Umidade] NUMERIC(18, 10), 
    [Energiakcal] NUMERIC(18, 10) NULL, 
    [Energiakg] NUMERIC(18, 10) NULL, 
    [Proteina] NUMERIC(18, 10) NULL, 
    [Lipidios] VARCHAR(50) NULL, 
    [Colesterol] VARCHAR(50) NULL, 
    [Carboidrato] NUMERIC(18, 10) NULL, 
    [Fibraalimentar] NUMERIC(18, 10) NULL, 
    [Cinzas] NUMERIC(18, 10) NULL, 
    [Calcio] NUMERIC(18, 10) NULL, 
    [Magnesio] VARCHAR(50) NULL, 
    [Manganes] VARCHAR(50) NULL, 
    [Fosforo] VARCHAR(50) NULL, 
    [Ferro] VARCHAR(50) NULL, 
    [Sodio] VARCHAR(50) NULL, 
    [Potassio] VARCHAR(50) NULL, 
    [Cobre] VARCHAR(50) NULL, 
    [Zinco] VARCHAR(50) NULL, 
    [Retinol] VARCHAR(50) NULL, 
    [Re] VARCHAR(50) NULL, 
    [Rae] VARCHAR(50) NULL, 
    [Tiamina] VARCHAR(50) NULL, 
    [Piridozina] VARCHAR(50) NULL, 
    [Riboflavina] VARCHAR(50) NULL, 
    [Niacina] VARCHAR(50) NULL, 
    [Vitaminac] VARCHAR(50) NULL

)