CREATE TABLE Alimentos (
    Codigo             bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CategoriaCodigo    int NOT NULL,
    Created            datetime NOT NULL DEFAULT GETDATE(),
    Updated            datetime NOT NULL DEFAULT GETDATE(),
    NumeroAlimento     int NOT NULL,
    Descricao          varchar(255) NOT NULL,
    Umidade            numeric(18, 10),
    EnergiaKcal        numeric(18, 10) NULL,
    EnergiaKg          numeric(18, 10) NULL,
    Proteina           numeric(18, 10) NULL,
    Lipidios           varchar(50) NULL,
    Colesterol         varchar(50) NULL,
    Carboidrato        numeric(18, 10) NULL,
    FibraAlimentar     numeric(18, 10) NULL,
    Cinzas             numeric(18, 10) NULL,
    Calcio             numeric(18, 10) NULL,
    Magnesio           varchar(50) NULL,
    Manganes           varchar(50) NULL,
    Fosforo            varchar(50) NULL,
    Ferro              varchar(50) NULL,
    Sodio              varchar(50) NULL,
    Potassio           varchar(50) NULL,
    Cobre              varchar(50) NULL,
    Zinco              varchar(50) NULL,
    Retinol            varchar(50) NULL,
    RE                 varchar(50) NULL,
    RAE                varchar(50) NULL,
    Tiamina            varchar(50) NULL,
    Piridozina         varchar(50) NULL,
    Riboflavina        varchar(50) NULL,
    Niacina            varchar(50) NULL,
    VitaminaC          varchar(50) NULL
);
