CREATE TABLE [dbo].[Notascortesisu]
(
	[Id] BIGINT NOT NULL PRIMARY KEY,
	[Year] [bigint] not null,
	[Numeroedicao] char(1) not null,
	[Codigoinstituicaoensino] [bigint] IDENTITY(1,1) not null,
	[Nomeinstituicao] varchar(500) not null,
	[Siglainstituicao] varchar(255) not null,
	[Organizacaoacademica] varchar(255) not null,
	[Categoriaorganizacao] varchar(255) not null,
	[Nomecampus] varchar(500) not null,
	[Nomemunicipiocampus] varchar(500) not null,
	[Ufcampus] varchar(2) not null,
	[Regiaocampus] varchar(50) not null,
	[Codigocurso] bigInt not null,
	[Nomecurso] varchar(500) not null,
	[Descricaograu] varchar(500) not null,
	[Turno] varchar(100) not null,
	[Modoconcorrencia] varchar(500) not null,
	[Desricaomodoconcorrencia] varchar(1000) not null,
	[Bonusacaoafirmativa] decimal not null,
	[Quantidadevagas] [bigint] not null,
	[Notacorte] decimal not null,
	[Quantidadeinscricoes] [bigint] not null,
)