CREATE TABLE [Pessoasfordev] (
    [Nome] VARCHAR (2000) DEFAULT ('') NOT NULL,
    [Idade] [bigint]            DEFAULT ((0)) NOT NULL,
    [Cpf] VARCHAR (12)   DEFAULT ('') NOT NULL,
    [Rg] VARCHAR (12)   DEFAULT ('') NOT NULL,
    [Datanascimento] VARCHAR (10)   DEFAULT ('') NOT NULL,
    [Sexo] VARCHAR (20)   DEFAULT ('Masculino') NOT NULL,
    [Signo] VARCHAR (30)   DEFAULT ('') NOT NULL,
    [Mae] VARCHAR (2000) DEFAULT ('') NOT NULL,
    [Pai] VARCHAR (2000) DEFAULT ('') NOT NULL,
    [Email] VARCHAR (500)  DEFAULT ('') NOT NULL,
    [Senha] VARCHAR (50)   DEFAULT ('') NOT NULL,
    [Cep] VARCHAR (8)    DEFAULT ('') NOT NULL,
    [Endereco] VARCHAR (1000) DEFAULT ('') NOT NULL,
    [Numero] [bigint]            DEFAULT ((0)) NOT NULL,
    [Bairro] VARCHAR (500)  DEFAULT ('') NOT NULL,
    [Cidade] VARCHAR (1000) DEFAULT ('') NOT NULL,
    [Estado] CHAR (2)       DEFAULT ('MG') NOT NULL,
    [Telefonefixo] VARCHAR (50)   DEFAULT ('') NOT NULL,
    [Celular] VARCHAR (50)   DEFAULT ('') NOT NULL,
    [Altura] VARCHAR (10)   DEFAULT ('') NOT NULL,
    [Peso] [bigint]            DEFAULT ((0)) NOT NULL,
    [Tiposanguineo] VARCHAR (3)    DEFAULT ('') NOT NULL,
    [Corfavorita] VARCHAR (30)   DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([Cpf] ASC)
);
